POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hbWUyIiwiaWQiOiI2MjAzZjZhMzlmNTE5ZTA0ZDBmNjA4NWQiLCJpYXQiOjE2NDQ1NzE0NjYsImV4cCI6MTY0NDU3NTA2Nn0.azAQI8YsfXYoKqOHE9KQfyddgLYRH1jFawXK9QxvgDo

{
    "title": "Title",
    "author": "Name ",
    "url": "www.url.com",
    "likes": 1
}